[package]
edition = "2024"
name = "blueshift_vault_client"
version = "0.1.0"

# 显式定义库
[lib]
name = "blueshift_vault_client"
path = "src/lib.rs"

# 显式定义二进制文件 (你的测试脚本)
[[bin]]
name = "blueshift_test"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
borsh = { version = "1.6.0", default-features = false, features = [
  "derive",
  "std",
], optional = false }
num-derive = "0.4"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }
solana-account-info = "3.1.0"
solana-commitment-config = "3.1.0"
solana-cpi = "3.1.0"
solana-instruction = "3.1.0"
solana-program-error = "3.0.0"
solana-pubkey = "4.0.0"
solana-rpc-client = "3.1.7"
solana-sdk = "3.0.0"
solana-system-interface = "3.0.0"
solana-transaction = "3.0.2"
thiserror = "2.0.18"
